baseURL = 'https://AntonioBisconti.github.io/personal_blog/'
languageCode = 'it'
title = 'antoniobisconti'
theme = 'PaperMod'


enableEmoji = true
DefaultContentLanguage= "it"
#copyright = "riservato"




[privacy]
  [privacy.instagram]
    disable = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true



#Markup per Simboli matematici
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\\[', '\\]'], ['$$', '$$']]
          inline = [['\\(', '\\)'], ['$', '$']]



[markup.goldmark.renderer]
  unsafe = true


  [markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true 
  style = "monokai"



[params]
#label.icon= "logo.svg"
math = true
comments= true
ShowShareButtons = true
ShowReadingTime = true
ShowToc = true
ShowCodeCopyButtons = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
description = "forse questa é la descrizione che appare su google? potrebbe essere, se effettivamente é"

#Questo serve per il logo nel header del sito, non per la favicon
label.icon="logo2.png"

 
  [params.assets]
  disableHLJS= true 
  favicon = "/assets/favicon.ico"
  favicon16x16 = "/assets/favicon-16x16.png"
  favicon32x32 = "/assets/favicon-32x32.png"
  apple_touch_icon = "/assets/apple-touch-icon.png"
  #android_chrome192x192= "/assets/android-chrome-192x192.png"
  #android_chrome192x192= "/assets/android-chrome-512x512.png"
 

  [params.giscus]
  repo = "antoniobisconti/commenti_sito"
  repoID = "R_kgDOLbGZLA"
  category = "Q&A"
  categoryID = "DIC_kwDOLbGZLM4CdsDo"
  mapping = "title"
  inputPosition = "bottom"
  lang = 'it'
  theme = "dark"
  


  [params.homeInfoParams]
  Title = "Un blog di espressione" 
  Content = """
  **Ciao**! :wave: Sonto Antonio, ho 21 anni e studio fisica a Palermo.

  Ho creato questo sito principalmente per farmi da archivio. In particolare trovate:
  - :white_small_square: Racconti della mia vita universitaria (abbastanza disagiata)
  - :white_small_square: Mie tentativi (fallimentari) di programmare
  - :white_small_square: Altre passioni varie

Porto la mia esperienza, non sono un esperto in niente di quello che scrivo. Ho voglia semplicemente di raccontarmi un po'; se 
a qualcuno le cose di cui parlo tornano utili ancora meglio. 
Se mi vuolete contattare questa é la mia email :postbox: antonio.bisconti02@gmail.com. 

Sono molto poco attivo su Instagram e vorrei, in futuro, pubblicare dei video su youtube.
  """

  [[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/antonio.bisconti_/"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/channel/UCxQMjDLyRJ--OybhBWPjkyw"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/AntonioBisconti"




[[menu.main]]
identifier = "archives"
name = "Tutti i Post"
url= "/archives"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20









