baseURL = 'https://AntonioBisconti.github.io/personal_blog/'
languageCode = 'en-us'
title = 'antoniobisconti'
theme = 'PaperMod'


enableEmoji = true
#Markup per Simboli matematici
#[markup]
#  [markup.goldmark]
#    [markup.goldmark.extensions]
#      [markup.goldmark.extensions.passthrough]
#        enable = true
#        [markup.goldmark.extensions.passthrough.delimiters]
#          block = [['\[', '\]'], ['$$', '$$']]
#          inline = [['\(', '\)']]

  [markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true 
  style = "monokai"


[params]
math = true
comments= true
#ShowShareButtons = true
ShowReadingTime = true
ShowToc = true
ShowCodeCopyButtons = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
description = "forse questa é la descrizione che appare su google? potrebbe essere, se effettivamente é"






  [params.homeInfoParams]
  Title = "Un blog a caso"
  Content = """
  Ciao! :wave: Studio Fisica a palermo, scrivo cose a caso se vi va leggetele. _In particolare_ questo trovate:

  - La mia vita universitaria (abbastanza disagiata)
  - Mie tentativi (fallimentari) di programmare
  - Robe varie

   se adesso riprendo a scrivere io mi chiedo perché non si riesca a fare il rander della lista, :pencil:
  """

  [[params.socialIcons]]
  name = "x"
  url = "https://x.com/"

  [[params.socialIcons]]
  name = "stackoverflow"
  url = "https://stackoverflow.com"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/"




[[menu.main]]
identifier = "archives"
name = "Archivio"
url= "/archives"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20









